services:
  aquachile-api:
    container_name: aquachile-api
    image: aquachile-api
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    depends_on:
      - aquachile-db

  aquachile-db:
    image: oracleinanutshell/oracle-xe-11g
    container_name: aquachile-db
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_PASSWORD=oracle

