@startuml ER-Diagram
hide empty methods
skinparam linetype ortho


entity BaseModel {
    * id : number <<generated>>
    --
    * created_at : timestamp
    * updated_at : timestamp
    * deleted_at : timestamp
    * version: number
}

entity Role {
    * name : text
    * description : text
}

entity User {
    * username : text
    * password : text
    --
    * role_id : number <<FK>>
}

entity Administrative {
    * name : text
    --
    * user_id : number <<FK>>
}

entity Admin {
    * name : text
    --
    * user_id : number <<FK>>
}

entity ShiftManager {
    * name : text
    --
    * user_id : number <<FK>>
}


entity Area {
    * name : text
}

entity Line {
    * name : text
    --
    * area_id : number <<FK>>
    * user_id : number <<FK>>
}

entity Operator {
    * name : text
    * rut : text
    --
    * line_id : number <<FK>>
    * area_id : number <<FK>>
    user_id : number <<FK>>
}

entity Productivity {
    * packed_tons : number
    * tons_produced : number
    --
    * shift_id : uuid <<FK>>
    * line_id : number <<FK>>
}

entity LabelingQuality {
    * n_deviations : number
    * n_audits : number
    --
    * shift_id : uuid <<FK>>
    * line_id : number <<FK>>
}

entity Cleanliness {
    * done : boolean
    * comment : text
    --
    * shift_id : uuid <<FK>>
    * line_id : number <<FK>>
}

entity PeerObservations {
    * result : number
    --
    * shift_id : uuid <<FK>>
    * line_id : number <<FK>>
}

entity Security {
    * result : number
    --
    * shift_id : uuid <<FK>>
    * line_id : number <<FK>>
}

entity MonthlyProgrammingProgress {
    * mounthly_order : number
    --
    * shift_id : uuid <<FK>>
    * line_id : number <<FK>>
}

entity Shift{
    * id : uuid <<generated>>
    --
    * shift : text
    * end_time : timestamp <<nullable>>
    --
    * shiftmanager_id : number <<FK>>
}

note bottom of BaseModel
    This is the base entity
    for all entities.
    Excluding the Shifts entity.
end note

Line ||--|| User
User ||--|| Administrative
User ||--|| Admin
ShiftManager ||--|| User
Operator |o--|| User
User }o--|| Role
Operator }o--|| Line
Operator }o--|| Area
Area ||--o{ Line

Shift }o--|| ShiftManager

Productivity ||--|| Shift
LabelingQuality ||--|| Shift
Cleanliness ||--|| Shift
PeerObservations ||--|| Shift
Security ||--|| Shift
MonthlyProgrammingProgress |o--o| Shift

Line ||--|| Productivity
Line ||--|| LabelingQuality
Line ||--|| Cleanliness
Line ||--|| PeerObservations
Line ||--|| Security
Line ||--|| MonthlyProgrammingProgress


@enduml
